name: Host Setup
run-name: >-
  ${{ 
    format('{0} ({1}): {2} by @{3}', 
      (github.event.inputs.environment || 'production'), 
      (github.event.inputs.action || 'plan'), 
      (github.event.inputs.reason || github.ref_name), 
      github.actor
    ) 
  }}

on:
  # push:
  #   branches:
  #     - main
  workflow_call:
    inputs:
      action:
        required: true
        type: string
      reason:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: 'main'

jobs:
  ansible-inventory:
    name: Generate Ansible Inventory
    uses: ./.github/workflows/_reusable.ansible.inventory.yaml
    secrets: inherit

  setup-host:
    needs: ansible-inventory
    name: Setup Host ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.ansible-inventory.outputs.hosts_matrix) }}
    uses: ./.github/workflows/_reusable.ansible.task.yaml
    with:
      action: ${{ github.event.inputs.action || 'plan' }}
      playbook: "ansible/host.setup.yaml"
      inventory_artifact: ${{ needs.ansible-inventory.outputs.artifact_name }}
      target_host: ${{ matrix.host }}
      branch: ${{ inputs.branch }}
    secrets: inherit

  incus-install:
    needs: [setup-host, ansible-inventory]
    name: Install Incus on Host ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.ansible-inventory.outputs.hosts_matrix) }}
    uses: ./.github/workflows/_reusable.ansible.task.yaml
    with:
      action: ${{ github.event.inputs.action || 'plan' }}
      playbook: "ansible/incus.install.yaml"
      inventory_artifact: ${{ needs.ansible-inventory.outputs.artifact_name }}
      target_host: ${{ matrix.host }}
      branch: ${{ inputs.branch }}
    secrets: inherit

  incus-master-init:
    needs: [setup-host, ansible-inventory, incus-install]
    name: Initialize Incus Master on Host ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.ansible-inventory.outputs.hosts_matrix) }}
    uses: ./.github/workflows/_reusable.ansible.task.yaml
    with:
      action: ${{ github.event.inputs.action || 'plan' }}
      playbook: "ansible/incus.master.init.yaml"
      inventory_artifact: ${{ needs.ansible-inventory.outputs.artifact_name }}
      target_host: ${{ matrix.host }}
      branch: ${{ inputs.branch }}
    secrets: inherit
